/*
 *  Program:    MaklerPoint System
 *  Module:     Main
 *  Language:   Java / Swing
 *  Date:       2010/09/03 13:10
 *  Web:        http://www.maklerpoint.de
 *  Version:    0.6.1
 *
 *  Copyright (C) 2010 Yves Hoppe.  All Rights Reserved.
 *  See License.txt or http://www.maklerpoint.de/copyright for details.
 *
 *  This software is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 *  above copyright notices for details.
 */

/*
 * NeuTag.java
 *
 * Created on Jul 19, 2010, 2:53:44 PM
 */
package de.maklerpoint.office.Gui.Configuration;

import de.maklerpoint.office.Tags.InitializeTags;
import de.maklerpoint.office.Tags.TagObj;
import de.maklerpoint.office.Tags.Tags;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Yves Hoppe <info at yves-hoppe.de>
 */
public class NeuTagDialog extends javax.swing.JDialog {
    
    private boolean update = false;
    private TagObj tag = null;
    private Color bgColor = null;
    private Color fontColor = null;

    /** Creates new form NeuTag */
    public NeuTagDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setUpTitle();
    }
    
    public NeuTagDialog(java.awt.Frame parent, boolean modal, TagObj tag) {
        super(parent, modal);
        this.tag = tag;
        this.update = true;
        initComponents();
        loadTag();
        setUpTitle();
    }
    
    private void setUpTitle() {
        if (update == false) {
            this.setTitle("Neue Markierung (Tag)");
        } else {
            this.setTitle("Markierung bearbeiten: " + tag.getName());
        }
    }
    
    private void loadTag() {
        if (update == false) {
            return;
        }
        
        fontColor = new Color(Integer.valueOf(tag.getFontColor()));
        bgColor = new Color(Integer.valueOf(tag.getTagColor()));
        
        this.fieldTagname.setText(tag.getName());
        this.panel_beispiel.setBackground(bgColor);
        this.label_beispiel.setForeground(fontColor);
        this.panel_beispiel.revalidate();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldTagname = new javax.swing.JTextField();
        btnBgcolor = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFontcolor = new javax.swing.JButton();
        panel_beispiel = new javax.swing.JPanel();
        label_beispiel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.maklerpoint.office.start.CRM.class).getContext().getResourceMap(NeuTagDialog.class);
        setTitle(resourceMap.getString("tagDialog.title")); // NOI18N
        setName("tagDialog"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        fieldTagname.setText(resourceMap.getString("fieldTagname.text")); // NOI18N
        fieldTagname.setName("fieldTagname"); // NOI18N

        btnBgcolor.setIcon(resourceMap.getIcon("btnBgcolor.icon")); // NOI18N
        btnBgcolor.setText(resourceMap.getString("btnBgcolor.text")); // NOI18N
        btnBgcolor.setName("btnBgcolor"); // NOI18N
        btnBgcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBgcolorActionPerformed(evt);
            }
        });

        btnSave.setMnemonic('S');
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.setPreferredSize(new java.awt.Dimension(90, 27));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic('A');
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(90, 27));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFontcolor.setIcon(resourceMap.getIcon("btnFontcolor.icon")); // NOI18N
        btnFontcolor.setText(resourceMap.getString("btnFontcolor.text")); // NOI18N
        btnFontcolor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFontcolor.setName("btnFontcolor"); // NOI18N
        btnFontcolor.setPreferredSize(new java.awt.Dimension(107, 28));
        btnFontcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFontcolorActionPerformed(evt);
            }
        });

        panel_beispiel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_beispiel.setName("panel_beispiel"); // NOI18N

        label_beispiel.setText(resourceMap.getString("label_beispiel.text")); // NOI18N
        label_beispiel.setName("label_beispiel"); // NOI18N

        javax.swing.GroupLayout panel_beispielLayout = new javax.swing.GroupLayout(panel_beispiel);
        panel_beispiel.setLayout(panel_beispielLayout);
        panel_beispielLayout.setHorizontalGroup(
            panel_beispielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_beispielLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(label_beispiel)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panel_beispielLayout.setVerticalGroup(
            panel_beispielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_beispiel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jSeparator1.setName("jSeparator1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_beispiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldTagname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFontcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBgcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTagname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBgcolor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFontcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_beispiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBgcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBgcolorActionPerformed
        Color chColor = null;
        try {
            if (update == false) {
                chColor = JColorChooser.showDialog(this, "Hintergrundfarbe", Color.white);
            } else {
                chColor = JColorChooser.showDialog(this, "Hintergrundfarbe", Color.getColor(tag.getTagColor()));
            }
        } catch (NullPointerException e) {            
        }
        
        if(chColor == null)
            return;
        
        bgColor = chColor;
        
        this.panel_beispiel.setBackground(bgColor);
        this.panel_beispiel.revalidate();        
    }//GEN-LAST:event_btnBgcolorActionPerformed
    
    private void btnFontcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFontcolorActionPerformed
        Color chColor = null;
        
        if (update == false) {
            chColor = JColorChooser.showDialog(null, "Schriftfarbe", Color.black);
        } else {
            chColor = JColorChooser.showDialog(null, "Schriftfarbe", new Color(Integer.valueOf(tag.getFontColor())));
        }
        
        if(chColor == null) {
            return;
        }
        
        fontColor = chColor;
        
        this.label_beispiel.setForeground(fontColor);        
    }//GEN-LAST:event_btnFontcolorActionPerformed
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String oldname = null;
        
        if (update == false) {
            tag = new TagObj();
        } else {
            oldname = tag.getName();
        }
        
        tag.setTagColor(bgColor.toString());
        tag.setFontColor(fontColor.toString());
        tag.setName(this.fieldTagname.getText());
        
        
        if (!update) {
            Tags.addTag(tag);
        } else {
            Tags.updateTag(tag, oldname);
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NeuTagDialog dialog = new NeuTagDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBgcolor;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFontcolor;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldTagname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_beispiel;
    private javax.swing.JPanel panel_beispiel;
    // End of variables declaration//GEN-END:variables
}
