/*
 *  Program:    MaklerPoint System
 *  Module:     Main
 *  Language:   Java / Swing
 *  Date:       2010/09/03 13:10
 *  Web:        http://www.maklerpoint.de
 *  Version:    0.6.1
 *
 *  Copyright (C) 2010 Yves Hoppe.  All Rights Reserved.
 *  See License.txt or http://www.maklerpoint.de/copyright for details.
 *
 *  This software is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 *  above copyright notices for details.
 */

/*
 * PanelConfigurationSonstiges.java
 *
 * Created on 02.09.2010, 18:56:53
 */

package de.maklerpoint.office.Gui.Configuration;

import de.maklerpoint.office.System.Configuration.Config;

/**
 *
 * @author yves
 */
public class PanelConfigurationSonstiges extends javax.swing.JPanel implements ConfigurationPanelInterface {

    /** Creates new form PanelConfigurationSonstiges */
    public PanelConfigurationSonstiges() {
        initComponents();
    }

   

     public int getCategory() {
        return ConfigurationPanelTypes.VERSCHIEDENES;
    }

    public String getPanelName() {
        return "Programmstart";
    }

    public void loadSettings() {
        this.check_searchupdates.setSelected(Config.getConfigBoolean("updateCheck", true));
        this.check_showtipp.setSelected(Config.getConfigBoolean("showTipoftheday", true));
        this.check_showwiedervorlagen.setSelected(Config.getConfigBoolean("wiedervorlagenShow", true)); //TODO
        this.check_synchronizeLocaldatabase.setSelected(Config.getConfigBoolean("startupSynchronize", false)); //TODO
    }

    public void saveSettings() {
        Config.setBoolean("updateCheck", this.check_searchupdates.isSelected());
        Config.setBoolean("showTipoftheday", this.check_showtipp.isSelected());
        Config.setBoolean("wiedervorlagenShow", this.check_showwiedervorlagen.isSelected());
        Config.setBoolean("startupSynchronize", this.check_synchronizeLocaldatabase.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jToolTipLabel1 = new de.maklerpoint.office.Tools.JToolTipLabel();
        check_showtipp = new javax.swing.JCheckBox();
        check_showwiedervorlagen = new javax.swing.JCheckBox();
        check_searchupdates = new javax.swing.JCheckBox();
        check_synchronizeLocaldatabase = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.maklerpoint.office.start.CRM.class).getContext().getResourceMap(PanelConfigurationSonstiges.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jToolTipLabel1.setToolTipText(resourceMap.getString("jToolTipLabel1.toolTipText")); // NOI18N
        jToolTipLabel1.setName("jToolTipLabel1"); // NOI18N

        check_showtipp.setText(resourceMap.getString("check_showtipp.text")); // NOI18N
        check_showtipp.setName("check_showtipp"); // NOI18N

        check_showwiedervorlagen.setText(resourceMap.getString("check_showwiedervorlagen.text")); // NOI18N
        check_showwiedervorlagen.setName("check_showwiedervorlagen"); // NOI18N

        check_searchupdates.setSelected(true);
        check_searchupdates.setText(resourceMap.getString("check_searchupdates.text")); // NOI18N
        check_searchupdates.setName("check_searchupdates"); // NOI18N

        check_synchronizeLocaldatabase.setText(resourceMap.getString("check_synchronizeLocaldatabase.text")); // NOI18N
        check_synchronizeLocaldatabase.setName("check_synchronizeLocaldatabase"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(check_searchupdates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jToolTipLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_synchronizeLocaldatabase)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(check_showtipp)
                    .addComponent(check_showwiedervorlagen))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolTipLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_searchupdates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_synchronizeLocaldatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_showtipp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_showwiedervorlagen)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_searchupdates;
    private javax.swing.JCheckBox check_showtipp;
    private javax.swing.JCheckBox check_showwiedervorlagen;
    private javax.swing.JCheckBox check_synchronizeLocaldatabase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private de.maklerpoint.office.Tools.JToolTipLabel jToolTipLabel1;
    // End of variables declaration//GEN-END:variables

}
