/*
 *  Program:    MaklerPoint System
 *  Module:     Main
 *  Language:   Java / Swing
 *  Date:       2010/09/03 13:10
 *  Web:        http://www.maklerpoint.de
 *  Version:    0.6.1
 *
 *  Copyright (C) 2010 Yves Hoppe.  All Rights Reserved.
 *  See License.txt or http://www.maklerpoint.de/copyright for details.
 *
 *  This software is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 *  above copyright notices for details.
 */

/*
 * PanelEinrichtungInstallationstyp.java
 *
 * Created on 08.09.2010, 12:49:29
 */
package de.maklerpoint.office.Gui.Firstrun;

import de.maklerpoint.office.System.Configuration.Config;

/**
 *
 * @author yves
 */
public class PanelEinrichtungInstallationstyp extends javax.swing.JPanel implements iAssistent {

    private EinrichtungsAssistentDialog as;
    int next = -1;

    /** Creates new form PanelEinrichtungInstallationstyp */
    public PanelEinrichtungInstallationstyp() {
        initComponents();
    }

    public int getId() {
        return 1;
    }

    public String getStepName() {
        return "Installationstyp";
    }

    public void loadSettings(EinrichtungsAssistentDialog as) {
        this.as = as;
    }

    public boolean validateSettings() {
        return true;
    }

    public void saveSettings() {
        if (this.btnEinzel.isSelected()) {
            Config.setInt("installationTyp", EinrichtungsHelper.EINZELPLATZ);
        } else if (this.btnNetzwerk.isSelected()) {
            Config.setInt("installationTyp", EinrichtungsHelper.NETZWERK);
        } else if (this.btnConnect.isSelected()) {
            Config.setInt("installationTyp", EinrichtungsHelper.CONNECT);
        }
    }

    public int next() {
        return next;
    }

    private void netzwerkInstall() {
        try {
            next = 3;
            as.wiz.next(as);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void connectInstall() {
        try {
            next = 2;
            as.wiz.next(as);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void einzelInstall() {
        try {
            next = 4;
            as.wiz.next(as);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTyp = new javax.swing.ButtonGroup();
        btnEinzel = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnNetzwerk = new javax.swing.JRadioButton();
        btnConnect = new javax.swing.JRadioButton();
        labelConnect = new javax.swing.JLabel();
        labelEinzel = new javax.swing.JLabel();
        label_netzwerk = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(478, 452));

        grpTyp.add(btnEinzel);
        btnEinzel.setSelected(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.maklerpoint.office.start.CRM.class).getContext().getResourceMap(PanelEinrichtungInstallationstyp.class);
        btnEinzel.setText(resourceMap.getString("btnEinzel.text")); // NOI18N
        btnEinzel.setContentAreaFilled(false);
        btnEinzel.setIcon(resourceMap.getIcon("btnEinzel.icon")); // NOI18N
        btnEinzel.setIconTextGap(6);
        btnEinzel.setName("btnEinzel"); // NOI18N
        btnEinzel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEinzelActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        grpTyp.add(btnNetzwerk);
        btnNetzwerk.setText(resourceMap.getString("btnNetzwerk.text")); // NOI18N
        btnNetzwerk.setActionCommand(resourceMap.getString("btnNetzwerk.actionCommand")); // NOI18N
        btnNetzwerk.setContentAreaFilled(false);
        btnNetzwerk.setIcon(resourceMap.getIcon("btnNetzwerk.icon")); // NOI18N
        btnNetzwerk.setIconTextGap(6);
        btnNetzwerk.setName("btnNetzwerk"); // NOI18N
        btnNetzwerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetzwerkActionPerformed(evt);
            }
        });

        grpTyp.add(btnConnect);
        btnConnect.setText(resourceMap.getString("btnConnect.text")); // NOI18N
        btnConnect.setContentAreaFilled(false);
        btnConnect.setIcon(resourceMap.getIcon("btnConnect.icon")); // NOI18N
        btnConnect.setIconTextGap(6);
        btnConnect.setName("btnConnect"); // NOI18N
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        labelConnect.setText(resourceMap.getString("labelConnect.text")); // NOI18N
        labelConnect.setName("labelConnect"); // NOI18N
        labelConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConnectMouseClicked(evt);
            }
        });

        labelEinzel.setText(resourceMap.getString("labelEinzel.text")); // NOI18N
        labelEinzel.setName("labelEinzel"); // NOI18N
        labelEinzel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEinzelMouseClicked(evt);
            }
        });

        label_netzwerk.setText(resourceMap.getString("label_netzwerk.text")); // NOI18N
        label_netzwerk.setName("label_netzwerk"); // NOI18N
        label_netzwerk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_netzwerkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEinzel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEinzel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNetzwerk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelConnect)
                            .addComponent(label_netzwerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnEinzel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEinzel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(label_netzwerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNetzwerk))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnConnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEinzelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEinzelActionPerformed
        einzelInstall();
    }//GEN-LAST:event_btnEinzelActionPerformed

    private void btnNetzwerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetzwerkActionPerformed
        netzwerkInstall();
    }//GEN-LAST:event_btnNetzwerkActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        connectInstall();
    }//GEN-LAST:event_btnConnectActionPerformed

    private void label_netzwerkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_netzwerkMouseClicked
        netzwerkInstall();
    }//GEN-LAST:event_label_netzwerkMouseClicked

    private void labelConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConnectMouseClicked
        connectInstall();
    }//GEN-LAST:event_labelConnectMouseClicked

    private void labelEinzelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEinzelMouseClicked
        einzelInstall();
    }//GEN-LAST:event_labelEinzelMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton btnConnect;
    public javax.swing.JRadioButton btnEinzel;
    public javax.swing.JRadioButton btnNetzwerk;
    public javax.swing.ButtonGroup grpTyp;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel labelConnect;
    public javax.swing.JLabel labelEinzel;
    public javax.swing.JLabel label_netzwerk;
    // End of variables declaration//GEN-END:variables
}
