/*
 *  Program:    MaklerPoint System
 *  Module:     Main
 *  Language:   Java / Swing
 *  Date:       2010/09/03 13:10
 *  Web:        http://www.maklerpoint.de
 *  Version:    0.6.1
 *
 *  Copyright (C) 2010 Yves Hoppe.  All Rights Reserved.
 *  See License.txt or http://www.maklerpoint.de/copyright for details.
 *
 *  This software is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 *  above copyright notices for details.
 */

/*
 * WaehrungenDialog.java
 *
 * Created on Aug 9, 2010, 12:32:44 PM
 */

package de.maklerpoint.office.Gui.Waehrungen;

import de.maklerpoint.office.Database.DatabaseConnection;
import de.maklerpoint.office.Exception.ShowException;
import de.maklerpoint.office.Gui.Exception.ExceptionDialogGui;
import de.maklerpoint.office.Logging.Log;
import de.maklerpoint.office.Registry.VersicherungsRegistry;
import de.maklerpoint.office.Waehrungen.Tools.WaehrungenSQLMethods;
import de.maklerpoint.office.Waehrungen.WaehrungenObj;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yves Hoppe <info at yves-hoppe.de>
 */
public class WaehrungenDialog extends javax.swing.JDialog {

    private WaehrungenObj currentWaehrung = null;
    private WaehrungenObj[] waehrungen = null;

    /** Creates new form WaehrungenDialog */
    public WaehrungenDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.waehrungen = VersicherungsRegistry.getWaehrungen(true);
        initComponents();
    }

    private void loadWaehrungen() {
        if(waehrungen == null) {
            // TODO Handling von nicht vorhandenen Währungen
            System.out.println("Keine Währungen vorhanden");
            return;
        }

        Object[] columnnames = new Object[]{"Hidden", "Sortierung", "ISO-Code", "Bezeichnung", "Neuanlage"};

        Object data[][] = new Object[waehrungen.length][5];

        for(int i = 0; i < waehrungen.length; i++) {
            data[i][0] = waehrungen[i];
            data[i][1] = waehrungen[i].getOrdering();
            data[i][2] = waehrungen[i].getIsocode();
            data[i][3] = waehrungen[i].getBezeichnung();
            data[i][4] = waehrungen[i].isNeuanlage();
        }

        this.table_waehrungen.setModel(new DefaultTableModel(data, columnnames));
        this.table_waehrungen.removeColumn(table_waehrungen.getColumn(0));
        this.table_waehrungen.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.table_waehrungen.revalidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNeu = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        field_search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_waehrungen = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_bezeichnung = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        field_ordering = new javax.swing.JTextField();
        field_isocode = new javax.swing.JTextField();
        check_neuanlage = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.maklerpoint.office.start.CRM.class).getContext().getResourceMap(WaehrungenDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        btnNeu.setIcon(resourceMap.getIcon("btnNeu.icon")); // NOI18N
        btnNeu.setMnemonic('N');
        btnNeu.setText(resourceMap.getString("btnNeu.text")); // NOI18N
        btnNeu.setFocusable(false);
        btnNeu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnNeu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNeu.setName("btnNeu"); // NOI18N
        btnNeu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNeu);

        btnDelete.setIcon(resourceMap.getIcon("btnDelete.icon")); // NOI18N
        btnDelete.setMnemonic('L');
        btnDelete.setText(resourceMap.getString("btnDelete.text")); // NOI18N
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDelete);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(resourceMap.getIcon("jLabel6.icon")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(73, 16));
        jToolBar1.add(jLabel6);

        field_search.setName("field_search"); // NOI18N
        field_search.setPreferredSize(new java.awt.Dimension(120, 25));
        field_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_searchKeyTyped(evt);
            }
        });
        jToolBar1.add(field_search);

        btnSearch.setIcon(resourceMap.getIcon("btnSearch.icon")); // NOI18N
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSearch);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        table_waehrungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sortierung", "ISO-Code", "Bezeichnung", "Neuanlage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_waehrungen.setName("table_waehrungen"); // NOI18N
        loadWaehrungen();
        table_waehrungen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_waehrungenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_waehrungen);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        field_bezeichnung.setName("field_bezeichnung"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        field_ordering.setText(resourceMap.getString("field_ordering.text")); // NOI18N
        field_ordering.setName("field_ordering"); // NOI18N

        field_isocode.setName("field_isocode"); // NOI18N

        check_neuanlage.setText(resourceMap.getString("check_neuanlage.text")); // NOI18N
        check_neuanlage.setName("check_neuanlage"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(field_ordering, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(check_neuanlage, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addComponent(field_bezeichnung, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(field_isocode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_bezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_isocode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(field_ordering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_neuanlage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_searchKeyTyped
        if(field_search.getText().length() > 3)
            searchTable();
}//GEN-LAST:event_field_searchKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchTable();
}//GEN-LAST:event_btnSearchActionPerformed

    private void table_waehrungenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_waehrungenMouseClicked
        int row = this.table_waehrungen.getSelectedRow();

        if(row == -1)
            return;

        if(currentWaehrung != null) {
            checkTableForUpdate();
        }

        WaehrungenObj waehrung = (WaehrungenObj) table_waehrungen.getModel().getValueAt(row, 0);

        if(waehrung == null)
            return;

        currentWaehrung = waehrung;

        this.field_bezeichnung.setText(waehrung.getBezeichnung());
        this.field_isocode.setText(waehrung.getIsocode());
        this.field_ordering.setText("" + waehrung.getOrdering());
        this.check_neuanlage.setSelected(waehrung.isNeuanlage());
}//GEN-LAST:event_table_waehrungenMouseClicked

    /**
     * 
     */

    public void searchTable() {
        int result = table_waehrungen.getSearchable().search(field_search.getText());

        if(result == -1)
            return;

        if(currentWaehrung != null) {
            checkTableForUpdate();
        }

        WaehrungenObj waehrung = (WaehrungenObj) table_waehrungen.getModel().getValueAt(result, 0);

        if(waehrung == null)
            return;

        currentWaehrung = waehrung;

        this.field_bezeichnung.setText(waehrung.getBezeichnung());
        this.field_isocode.setText(waehrung.getIsocode());
        this.field_ordering.setText("" + waehrung.getOrdering());
        this.check_neuanlage.setSelected(waehrung.isNeuanlage());        
    }

    /**
     * 
     */

    public void checkTableForUpdate() {
        if(!this.field_bezeichnung.getText().equalsIgnoreCase(currentWaehrung.getBezeichnung()) ||
            !this.field_isocode.getText().equalsIgnoreCase(currentWaehrung.getIsocode()) ||
            Integer.valueOf(this.field_ordering.getText()) != currentWaehrung.getOrdering()
            || this.check_neuanlage.isSelected() != currentWaehrung.isNeuanlage()
            )  {
            int answer = JOptionPane.showConfirmDialog(null, "Wollen Sie die geänderte Währung speichern?",
                        "Datensatz speichern", JOptionPane.YES_NO_OPTION);

            if(answer == JOptionPane.YES_OPTION) {
                currentWaehrung.setBezeichnung(this.field_bezeichnung.getText());
                currentWaehrung.setIsocode(this.field_isocode.getText());
                currentWaehrung.setOrdering(Integer.valueOf(this.field_ordering.getText()));
                currentWaehrung.setNeuanlage(this.check_neuanlage.isSelected());

                try {
                    boolean success = WaehrungenSQLMethods.updatewaehrungen(DatabaseConnection.open(), currentWaehrung);

                    if(success == false) {
                        System.out.println("ADD Exception: Das geupdate Währungs Objekt wurde nicht gefunden.");
                    }

                } catch(SQLException e) {
                    Log.databaselogger.fatal("Fehler: Konnte Währung nicht speichern.", e);
                    ShowException.showException("Die Währung konnte nicht gespeichert werden.",
                            ExceptionDialogGui.LEVEL_WARNING, e,
                            "Datenbankfehler: Konnte Währung nicht speichern");                    
                }
                
            }
        }
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WaehrungenDialog dialog = new WaehrungenDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNeu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox check_neuanlage;
    private javax.swing.JTextField field_bezeichnung;
    private javax.swing.JTextField field_isocode;
    private javax.swing.JTextField field_ordering;
    private javax.swing.JTextField field_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTable table_waehrungen;
    // End of variables declaration//GEN-END:variables

}
