/*
 *  Program:    MaklerPoint System
 *  Module:     Main
 *  Language:   Java / Swing
 *  Date:       2010/09/03 13:10
 *  Web:        http://www.maklerpoint.de
 *  Version:    0.6.1
 *
 *  Copyright (C) 2010 Yves Hoppe.  All Rights Reserved.
 *  See License.txt or http://www.maklerpoint.de/copyright for details.
 *
 *  This software is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 *  above copyright notices for details.
 */

/*
 * EnterLicenseDialog.java
 *
 * Created on Jul 24, 2010, 6:05:32 PM
 */

package de.maklerpoint.office.Gui.License;

import de.maklerpoint.office.start.CRM;
import de.maklerpoint.office.Konstanten.MPointKonstanten;
import de.acyrance.licensor.Config.LicenseConfig;
import de.acyrance.licensor.License;
import de.acyrance.licensor.Tools.JTextFieldLimit;
import javax.swing.JOptionPane;

/**
 *
 * @author Yves Hoppe <info at yves-hoppe.de>
 */
public class EnterLicenseDialog extends javax.swing.JDialog {

    private int f41lc0unt = 0;
    private String[] args = null;

    /** Creates new form EnterLicenseDialog */
    public EnterLicenseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(MPointKonstanten.icon);
        setOUp0044();
    }

    public EnterLicenseDialog(java.awt.Frame parent, boolean modal, String[] args) {
        super(parent, modal);
        this.args = args;
        initComponents();
        this.setIconImage(MPointKonstanten.icon);
        this.btnActivateInternet.setVisible(false);
        this.btnActivateTelefon.setVisible(false);
        setOUp0044();
    }

    private void setOUp0044() {
        this.field_serial001.setDocument(new JTextFieldLimit(5, true));
        this.field_serial002.setDocument(new JTextFieldLimit(5, true));
        this.field_serial003.setDocument(new JTextFieldLimit(5, true));
        this.field_serial004.setDocument(new JTextFieldLimit(5, true));
        this.field_serial005.setDocument(new JTextFieldLimit(5, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field_lizenznehmer = new javax.swing.JTextField();
        error_text = new javax.swing.JLabel();
        btnActivateTelefon = new javax.swing.JButton();
        btnActivateInternet = new javax.swing.JButton();
        btnActivate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        field_serial001 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        field_serial002 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        field_serial003 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        field_serial004 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        field_serial005 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MaklerPoint Aktivierung"); // NOI18N
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/acyrance/licensor/Gui/resources/blue-aktivierung.jpg"))); // NOI18N

        jLabel2.setText("Lizenznehmer:");

        field_lizenznehmer.setMinimumSize(new java.awt.Dimension(80, 27));
        field_lizenznehmer.setPreferredSize(new java.awt.Dimension(200, 27));

        error_text.setForeground(new java.awt.Color(255, 0, 0));
        error_text.setText("Der eingegebene Lizenschlüssel ist nicht gültig!");
        error_text.setVisible(false);

        btnActivateTelefon.setMnemonic('T');
        btnActivateTelefon.setText("Telefonische Aktivierung");

        btnActivateInternet.setMnemonic('A');
        btnActivateInternet.setText("Aktivierung per Internet");

        btnActivate.setMnemonic('A');
        btnActivate.setText("Aktivieren");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic('A');
        btnCancel.setText("Abrechen");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Lizenzschlüssel:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);

        field_serial001.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(field_serial001, new java.awt.GridBagConstraints());

        jLabel7.setText(" - ");
        jPanel1.add(jLabel7, new java.awt.GridBagConstraints());

        field_serial002.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(field_serial002, new java.awt.GridBagConstraints());

        jLabel5.setText(" - ");
        jPanel1.add(jLabel5, new java.awt.GridBagConstraints());

        field_serial003.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(field_serial003, new java.awt.GridBagConstraints());

        jLabel4.setText(" - ");
        jPanel1.add(jLabel4, new java.awt.GridBagConstraints());

        field_serial004.setMinimumSize(new java.awt.Dimension(50, 25));
        field_serial004.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(field_serial004, new java.awt.GridBagConstraints());

        jLabel6.setText(" - ");
        jPanel1.add(jLabel6, new java.awt.GridBagConstraints());

        field_serial005.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(field_serial005, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnActivateTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActivateInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActivate))
                    .addComponent(error_text, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(field_lizenznehmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_lizenznehmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivateTelefon)
                    .addComponent(btnActivateInternet)
                    .addComponent(btnActivate)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateActionPerformed
        this.btnActivate.setEnabled(false);
        String lizenznehmer = this.field_lizenznehmer.getText().trim();
        String serialOO423 = this.field_serial001.getText() + "-" + this.field_serial002.getText() + "-"
                + this.field_serial003.getText() + "-" + this.field_serial004.getText() + "-" + this.field_serial005.getText();

//        System.out.println("Sn given: " + serialOO423);
        try {
            if(f41lc0unt <= 3) {
//                System.out.println("Lizenznehmer: " + lizenznehmer);
//                System.out.println("Serial: " + serialOO423);
                String valO04 = License.validate(lizenznehmer, serialOO423);
                valO04 = valO04 + "OO004";
                if(valO04.equals("faf4s!l3sOO004")) {
                    LicenseConfig.setBoolean("serial", true);
                    LicenseConfig.setBoolean("activated", false);
                    LicenseConfig.set("licensor", lizenznehmer);
                    LicenseConfig.set("licenseKey", serialOO423);
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Das Produkt wurde erfolgreich aktiviert",
                                             "Willkommen bei MaklerPoint Office", JOptionPane.INFORMATION_MESSAGE);
                    CRM.launchAnmeldung(args);
                    this.dispose();
                } else {
//                    JOptionPane.showMessageDialog(null, "Der eingegebene Lizenzcode ist nicht gültig",
//                                             "Fehler: Falscher Lizenzcode", JOptionPane.ERROR_MESSAGE);
                    if(f41lc0unt == 0) {
                        this.setSize(this.getWidth(), this.getHeight() + 15);                    
                    }
                    this.error_text.setVisible(true);
                    f41lc0unt++;
                }
            } else {
                int anwser = JOptionPane.showConfirmDialog(null, "Sie haben zu häufig den falschen Lizenzcode eingegeben. Das Programm wird beendet",
                                             "Fehler: Falscher Lizenzcode", JOptionPane.OK_OPTION);
                System.exit(0);
            }
        } catch (Exception e) {
            System.out.println("ERROR VALIDATING SN");
            e.printStackTrace();
        }
        this.btnActivate.setEnabled(true);
    }//GEN-LAST:event_btnActivateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(103);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnterLicenseDialog dialog = new EnterLicenseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivate;
    private javax.swing.JButton btnActivateInternet;
    private javax.swing.JButton btnActivateTelefon;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel error_text;
    private javax.swing.JTextField field_lizenznehmer;
    private javax.swing.JTextField field_serial001;
    private javax.swing.JTextField field_serial002;
    private javax.swing.JTextField field_serial003;
    private javax.swing.JTextField field_serial004;
    private javax.swing.JTextField field_serial005;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
