/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NeuBriefDialog.java
 *
 * Created on 05.06.2011, 13:11:11
 */
package de.maklerpoint.office.Gui.Briefe;

import de.maklerpoint.office.Briefe.BriefCategoryObj;
import de.maklerpoint.office.Briefe.BriefObj;
import de.maklerpoint.office.Briefe.Tools.BriefeHelper;
import de.maklerpoint.office.Briefe.Tools.BriefeSQLMethods;
import de.maklerpoint.office.Database.DatabaseConnection;
import de.maklerpoint.office.Exception.ShowException;
import de.maklerpoint.office.Gui.Configuration.TagDialogHelper;
import de.maklerpoint.office.Gui.Exception.ExceptionDialogGui;
import de.maklerpoint.office.Gui.Tools.ComboBoxGetter;
import de.maklerpoint.office.Gui.Tools.MaximizeHelper;
import de.maklerpoint.office.Konstanten.Briefe;
import de.maklerpoint.office.Logging.Log;
import de.maklerpoint.office.Registry.BenutzerRegistry;
import de.maklerpoint.office.Tags.Tags;
import de.maklerpoint.office.Tools.FileTools;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Yves Hoppe <hoppe at maklerpoint.de>
 */
public class NeuBriefDialog extends javax.swing.JDialog {

    private boolean update = false;
    private BriefObj brief = null;
    private SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy HH:mm");

    /** Creates new form NeuBriefDialog */
    public NeuBriefDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.update = false;
        this.brief = null;
        initComponents();
        setUp();
    }

    public NeuBriefDialog(java.awt.Frame parent, boolean modal, BriefObj brief) {
        super(parent, modal);
        this.update = true;
        this.brief = brief;
        initComponents();
        setUp();
    }

    private void setUp() {
        this.setTitle("Neuer Brief / Fax / E-Mail");
        this.combo_type.setEnabled(true);
        this.combo_tag.setModel(new DefaultComboBoxModel(Tags.tags));
        this.combo_category.setModel(new DefaultComboBoxModel(ComboBoxGetter.getBriefCategoriesCombo(null)));
        this.combo_type.setModel(new DefaultComboBoxModel(Briefe.TYPES));
        loadBrief();
    }

    private void loadBrief() {
        if (brief == null) {
            return;
        }

        this.field_name.setText(brief.getName());
        this.field_file.setText(brief.getFullpath());
        this.combo_category.setSelectedItem(BriefeHelper.getBriefCategoryObj(brief.getCategoryId()));
        this.combo_tag.setSelectedItem(Tags.getTag(brief.getTag()));
        this.combo_type.setSelectedIndex(brief.getType());
        this.combo_type.setEnabled(false);

        this.label_checksum.setText(brief.getChecksum());
        this.label_created.setText(df.format(brief.getCreated()));
        this.label_modified.setText(df.format(brief.getModified()));
        this.label_creator.setText(BenutzerRegistry.getBenutzer(brief.getCreatorId(), true).toString());

        this.check_benutzer.setSelected(brief.isBenutzer());
        this.check_gesch.setSelected(brief.isGeschKunde());
        this.check_privat.setSelected(brief.isPrivatKunde());
        this.check_produkt.setSelected(brief.isProdukt());
        this.check_stoer.setSelected(brief.isStoerfall());
        this.check_vers.setSelected(brief.isVersicherer());
        this.check_vertrag.setSelected(brief.isBenutzer());

        this.text_beschreibung.setText(brief.getBeschreibung());
        this.text_commments.setText(brief.getComments());
        this.setTitle(brief.getName() + " (" + brief.getFullpath() + ")");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        paneBrief = new javax.swing.JTabbedPane();
        panel_basis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        btnMaxTextBeschreibung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_beschreibung = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo_tag = new javax.swing.JComboBox();
        btnTags = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_type = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        combo_category = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        field_file = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        panel_advanced = new javax.swing.JPanel();
        check_gesch = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        check_privat = new javax.swing.JCheckBox();
        check_vers = new javax.swing.JCheckBox();
        check_produkt = new javax.swing.JCheckBox();
        check_stoer = new javax.swing.JCheckBox();
        check_vertrag = new javax.swing.JCheckBox();
        check_benutzer = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        label_creator = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_checksum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_created = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_modified = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_commments = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btnMaxTextKommentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.maklerpoint.office.start.CRM.class).getContext().getResourceMap(NeuBriefDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        btnCancel.setMnemonic('A');
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 27));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setMnemonic('S');
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.setPreferredSize(new java.awt.Dimension(120, 27));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        paneBrief.setName("paneBrief"); // NOI18N

        panel_basis.setName("panel_basis"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        field_name.setText(resourceMap.getString("field_name.text")); // NOI18N
        field_name.setName("field_name"); // NOI18N

        btnMaxTextBeschreibung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/acyrance/CRM/Gui/resources/lupe.gif"))); // NOI18N
        btnMaxTextBeschreibung.setToolTipText(resourceMap.getString("btnMaxTextBeschreibung.toolTipText")); // NOI18N
        btnMaxTextBeschreibung.setName("btnMaxTextBeschreibung"); // NOI18N
        btnMaxTextBeschreibung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxTextBeschreibungActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        text_beschreibung.setColumns(20);
        text_beschreibung.setRows(5);
        text_beschreibung.setName("text_beschreibung"); // NOI18N
        jScrollPane1.setViewportView(text_beschreibung);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        combo_tag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tag.setName("combo_tag"); // NOI18N
        combo_tag.setPreferredSize(new java.awt.Dimension(200, 25));

        btnTags.setIcon(resourceMap.getIcon("btnTags.icon")); // NOI18N
        btnTags.setName("btnTags"); // NOI18N
        btnTags.setPreferredSize(new java.awt.Dimension(28, 26));
        btnTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagsActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_type.setName("combo_type"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        combo_category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_category.setName("combo_category"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        field_file.setName("field_file"); // NOI18N
        field_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                field_fileMouseClicked(evt);
            }
        });

        jSeparator4.setName("jSeparator4"); // NOI18N

        javax.swing.GroupLayout panel_basisLayout = new javax.swing.GroupLayout(panel_basis);
        panel_basis.setLayout(panel_basisLayout);
        panel_basisLayout.setHorizontalGroup(
            panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_basisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_basisLayout.createSequentialGroup()
                        .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_basisLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(33, 33, 33))
                            .addGroup(panel_basisLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnMaxTextBeschreibung))
                    .addGroup(panel_basisLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_basisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_basisLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(combo_category, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(panel_basisLayout.createSequentialGroup()
                        .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_basisLayout.createSequentialGroup()
                                .addComponent(combo_tag, 0, 376, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(field_file, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_basisLayout.setVerticalGroup(
            panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_basisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(combo_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_basisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMaxTextBeschreibung)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paneBrief.addTab(resourceMap.getString("panel_basis.TabConstraints.tabTitle"), panel_basis); // NOI18N

        panel_advanced.setName("panel_advanced"); // NOI18N

        check_gesch.setText(resourceMap.getString("check_gesch.text")); // NOI18N
        check_gesch.setName("check_gesch"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        check_privat.setText(resourceMap.getString("check_privat.text")); // NOI18N
        check_privat.setName("check_privat"); // NOI18N

        check_vers.setText(resourceMap.getString("check_vers.text")); // NOI18N
        check_vers.setName("check_vers"); // NOI18N

        check_produkt.setText(resourceMap.getString("check_produkt.text")); // NOI18N
        check_produkt.setName("check_produkt"); // NOI18N

        check_stoer.setText(resourceMap.getString("check_stoer.text")); // NOI18N
        check_stoer.setName("check_stoer"); // NOI18N

        check_vertrag.setText(resourceMap.getString("check_vertrag.text")); // NOI18N
        check_vertrag.setName("check_vertrag"); // NOI18N

        check_benutzer.setText(resourceMap.getString("check_benutzer.text")); // NOI18N
        check_benutzer.setName("check_benutzer"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        label_creator.setText(resourceMap.getString("label_creator.text")); // NOI18N
        label_creator.setName("label_creator"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        label_checksum.setText(resourceMap.getString("label_checksum.text")); // NOI18N
        label_checksum.setName("label_checksum"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        label_created.setText(resourceMap.getString("label_created.text")); // NOI18N
        label_created.setName("label_created"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        label_modified.setText(resourceMap.getString("label_modified.text")); // NOI18N
        label_modified.setName("label_modified"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        text_commments.setColumns(20);
        text_commments.setRows(5);
        text_commments.setName("text_commments"); // NOI18N
        jScrollPane2.setViewportView(text_commments);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        btnMaxTextKommentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/acyrance/CRM/Gui/resources/lupe.gif"))); // NOI18N
        btnMaxTextKommentar.setToolTipText(resourceMap.getString("btnMaxTextKommentar.toolTipText")); // NOI18N
        btnMaxTextKommentar.setName("btnMaxTextKommentar"); // NOI18N
        btnMaxTextKommentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxTextKommentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_advancedLayout = new javax.swing.GroupLayout(panel_advanced);
        panel_advanced.setLayout(panel_advancedLayout);
        panel_advancedLayout.setHorizontalGroup(
            panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_advancedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_gesch)
                            .addComponent(check_privat)
                            .addComponent(check_vers))
                        .addGap(18, 18, 18)
                        .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_stoer)
                            .addGroup(panel_advancedLayout.createSequentialGroup()
                                .addComponent(check_produkt)
                                .addGap(36, 36, 36)
                                .addComponent(check_benutzer))
                            .addComponent(check_vertrag))
                        .addGap(143, 143, 143))
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                        .addComponent(label_checksum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_advancedLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                        .addComponent(label_creator))
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addComponent(label_created))
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                        .addComponent(label_modified))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_advancedLayout.createSequentialGroup()
                        .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_advancedLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(33, 33, 33))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMaxTextKommentar)))
                .addContainerGap())
        );
        panel_advancedLayout.setVerticalGroup(
            panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_advancedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addComponent(check_privat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_gesch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_vers))
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_produkt)
                            .addComponent(check_benutzer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_stoer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_vertrag)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(label_checksum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_creator)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_created)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_modified)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_advancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnMaxTextKommentar))
                    .addGroup(panel_advancedLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        paneBrief.addTab(resourceMap.getString("panel_advanced.TabConstraints.tabTitle"), panel_advanced); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneBrief, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(paneBrief, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (this.update == false) {
            int dial = JOptionPane.NO_OPTION;
            dial = JOptionPane.showConfirmDialog(null, "Wollen Sie das Fenster wirklich schließen? Alle ihre Eingaben "
                    + "gehen in diesem Fall verloren.", "Wollen Sie das Fenster schließen?", JOptionPane.YES_NO_OPTION);
            if (dial == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            this.dispose();
        }
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (update == false) {
            brief = new BriefObj();
        }

        brief.setName(field_name.getText());
        brief.setFullpath(field_file.getText());

        BriefCategoryObj bcat = (BriefCategoryObj) this.combo_category.getSelectedItem();

        brief.setCategoryId(bcat.getId());

        brief.setTag(this.combo_tag.getSelectedItem().toString());
        brief.setType(this.combo_type.getSelectedIndex());

        brief.setBenutzer(check_benutzer.isSelected());
        brief.setGeschKunde(check_gesch.isSelected());
        brief.setPrivatKunde(check_privat.isSelected());
        brief.setProdukt(check_produkt.isSelected());
        brief.setStoerfall(check_stoer.isSelected());
        brief.setVersicherer(check_vers.isSelected());
        brief.setVertrag(check_vertrag.isSelected());

        brief.setBeschreibung(text_beschreibung.getText());
        brief.setComments(text_commments.getText());

        try {
            if (update) {
                BriefeSQLMethods.updateBriefe(DatabaseConnection.open(), brief);
            } else {
                brief.setCreated(new java.sql.Timestamp(System.currentTimeMillis()));
                BriefeSQLMethods.insertIntoBriefe(DatabaseConnection.open(), brief);
            }
        } catch (Exception e) {
            Log.databaselogger.fatal("Datenbankfehler: Konnte Brief nicht speichern", e);
            ShowException.showException("Bei der Speicherung des Briefes ist ein Datenbank Fehler aufgetretten. "
                    + "Sollte dieser häufiger auftretten wenden Sie sich bitte an den Support.",
                    ExceptionDialogGui.LEVEL_WARNING, e,
                    "Schwerwiegend: Konnte Brief nicht speichern");
        }

        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnMaxTextBeschreibungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxTextBeschreibungActionPerformed
        MaximizeHelper.openMax(this.text_beschreibung, "Beschreibung");
}//GEN-LAST:event_btnMaxTextBeschreibungActionPerformed

    private void btnTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagsActionPerformed
        TagDialogHelper.showTagDialog();
}//GEN-LAST:event_btnTagsActionPerformed

    private void btnMaxTextKommentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxTextKommentarActionPerformed
        MaximizeHelper.openMax(this.text_commments, "Kommentar");
    }//GEN-LAST:event_btnMaxTextKommentarActionPerformed

    private void field_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_fileMouseClicked
        String file = FileTools.openFile("Vorlage wählen..");

        if (file != null) {
            this.field_file.setText(file);
        }
    }//GEN-LAST:event_field_fileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NeuBriefDialog dialog = new NeuBriefDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMaxTextBeschreibung;
    private javax.swing.JButton btnMaxTextKommentar;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTags;
    private javax.swing.JCheckBox check_benutzer;
    private javax.swing.JCheckBox check_gesch;
    private javax.swing.JCheckBox check_privat;
    private javax.swing.JCheckBox check_produkt;
    private javax.swing.JCheckBox check_stoer;
    private javax.swing.JCheckBox check_vers;
    private javax.swing.JCheckBox check_vertrag;
    private javax.swing.JComboBox combo_category;
    private javax.swing.JComboBox combo_tag;
    private javax.swing.JComboBox combo_type;
    private javax.swing.JTextField field_file;
    private javax.swing.JTextField field_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_checksum;
    private javax.swing.JLabel label_created;
    private javax.swing.JLabel label_creator;
    private javax.swing.JLabel label_modified;
    private javax.swing.JTabbedPane paneBrief;
    private javax.swing.JPanel panel_advanced;
    private javax.swing.JPanel panel_basis;
    private javax.swing.JTextArea text_beschreibung;
    private javax.swing.JTextArea text_commments;
    // End of variables declaration//GEN-END:variables
}
